/*
	This code was generated by SQL Compact Code Generator version 1.3.0.7

	SQL Compact Code Generator was written by Christian Resma Helle (http://sqlcecodegen.codeplex.com)
	and is under the GNU General Public License version 2 (GPLv2)

	Generated: 07/13/2013 19:59:21
*/



using Microsoft.VisualStudio.TestTools.UnitTesting;
namespace DBHelperTest
{
    [TestClass]
    internal static class CollectionAssert
    {
        internal static void AllItemsAreNotNull<T>(System.Collections.Generic.IEnumerable<T> items)
        {
            foreach (var item in items) 
                Assert.IsNotNull(item);
        }
    }
}

