/*
	This code was generated by SQL Compact Code Generator version 1.3.0.7

	SQL Compact Code Generator was written by Christian Resma Helle (http://sqlcecodegen.codeplex.com)
	and is under the GNU General Public License version 2 (GPLv2)

	Generated: 07/13/2013 19:59:21
*/



namespace DBHelperTest
{
    using DBHelper;
using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
	public class DatabaseFileTest : DataAccessTestBase
	{
		[TestMethod]
		public void CreateDatabaseTest()
		{
			var databaseFile = @"C:\Users\Nho\Documents\Visual Studio 2012\Projects\DBHelper\DBHelper\db\EnghlistHelperDB.sdf_" + System.Guid.NewGuid().ToString().Replace("{", string.Empty).Replace("}", string.Empty) + ".sdf";
			EntityBase.ConnectionString = "Data Source='" + databaseFile + "'";
			EntityBase.Connection.Dispose();
			EntityBase.Connection = null;

			var actual = DatabaseFile.CreateDatabase();
			Assert.AreNotEqual(0, actual);

			EntityBase.ConnectionString = @"Data Source=C:\Users\Nho\Documents\Visual Studio 2012\Projects\DBHelper\DBHelper\db\EnghlistHelperDB.sdf; Password=123456a@";
			EntityBase.Connection.Dispose();
			EntityBase.Connection = null;
		}
	}
}

