/*
	This code was generated by SQL Compact Code Generator version 1.3.0.7

	SQL Compact Code Generator was written by Christian Resma Helle (http://sqlcecodegen.codeplex.com)
	and is under the GNU General Public License version 2 (GPLv2)

	Generated: 07/13/2013 19:59:21
*/



namespace DBHelper
{
	/// <summary>
	/// Helper class for generating the database file in runtime
	/// </summary>
	public static class DatabaseFile
	{
		/// <summary>
		/// Creates the database
		/// </summary>
		public static int CreateDatabase()
		{
			int resultCount = 0;

			using (var engine = new System.Data.SqlServerCe.SqlCeEngine(EntityBase.ConnectionString))
				engine.CreateDatabase();

			using (var transaction = EntityBase.Connection.BeginTransaction())
			using (var command = EntityBase.CreateCommand(transaction))
			{
				command.CommandText = "CREATE TABLE [EnglishSentences](ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, Content NVARCHAR(100), Level INT)";
				resultCount += command.ExecuteNonQuery();

				transaction.Commit();
			}

			return resultCount;
		}
	}
}

