/*
	This code was generated by SQL Compact Code Generator version 1.3.0.7

	SQL Compact Code Generator was written by Christian Resma Helle (http://sqlcecodegen.codeplex.com)
	and is under the GNU General Public License version 2 (GPLv2)

	Generated: 07/13/2013 19:59:21
*/



namespace DBHelper
{
	/// <summary>
	/// Represents the EnglishSentences table
	/// </summary>
	public partial class EnglishSentences
	{
		private System.Int32? _ID;
		/// <summary>
		/// Gets or sets the value of ID
		/// </summary>
		public System.Int32? ID
		{
			get { return _ID; }
			set
			{
				_ID = value;
			}
		}
		private System.String _Content;
		/// <summary>
		/// The Maximum Length the Content field allows
		/// </summary>
		public const int Content_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of Content
		/// </summary>
		public System.String Content
		{
			get { return _Content; }
			set
			{
				_Content = value;
				if (_Content != null && Content.Length > Content_Max_Length)
					throw new System.ArgumentException("Max length for Content is 100");
			}
		}
		private System.Int32? _Level;
		/// <summary>
		/// Gets or sets the value of Level
		/// </summary>
		public System.Int32? Level
		{
			get { return _Level; }
			set
			{
				_Level = value;
			}
		}
	}
}

